model: 
  name: unet3d_h100_custom
  type: cnn
  model_size: 499153191

framework: pytorch

workflow:
  generate_data: False
  train: True
  checkpoint: True

dataset:
  data_folder: data/unet3d/
  format: npz
  num_files_train: 64
  num_samples_per_file: 1
  record_length_bytes: 1048576
  record_length_bytes_stdev: 524288
  record_length_bytes_resize: 262144

reader:
  data_loader: pytorch
  batch_size: 2
  read_threads: 1
  file_shuffle: seed
  sample_shuffle: seed

train:
  epochs: 2
  computation_time: 0.1

checkpoint:
  checkpoint_folder: checkpoints/unet3d
  checkpoint_after_epoch: 2
  epochs_between_checkpoints: 1

metric:
  au: 0.90

profiling: 
  profiler: iostat
